baseURL = ""
languageCode = "ko"
title = "LogLee's Training Ground"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
summaryLength = 10
theme = "book"

[params]
  BookTheme = "light"
  BookSection = "docs"
  BookSearch = true
  BookToC = true
  BookLogo = '/images/de-landscape.png'
  BookLogoText = 'LogLee.dev'
  BookDateFormat = "January 2, 2006"
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "---------------------"  # 공백 문자 또는 separator 역할
  url = ""
  weight = 50

[[menu.after]]
  name = "GitHub link는 여기!"
  url = "https://github.com/SteveArseneLee"
  weight = 51
