baseURL = "https://stevearsenelee.github.io"
languageCode = "ko"
title = "LogLee's Training Ground"

defaultContentLanguage = "kr"
defaultContentLanguageInSubdir = false
summaryLength = 10

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  BookTheme = "auto"
  BookSection = ""
  BookSearch = true
  BookToC = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"