baseURL = "https://stevearsenelee.github.io"
languageCode = "ko"
title = "LogLee's Training Ground"

defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
summaryLength = 10

theme = "book"

[params]
  BookTheme = "auto"
  BookSection = "docs"
  BookSearch = true
  BookToC = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"